### ISSUE TITLE
Give example docker swarm deployment

### ISSUE THREAD

**Issue by jsenecal** [crazy-max/docker-librenms#1]
It would be nice if you added an example docker-compose.yml suitable for docker in swarm mode.

This should also provide separate web and poller using rrdcache and memcache for rrd storage and poller state exchange (already available, though I cannot figure how you are configuring them in the "app" service).

I'm currently running something like this [docker-compose.yml file](https://gist.github.com/jsenecal/ca255c2734d1f18b9eaeaf63037e3904) with most of the librenms stuff from the [other available image](https://github.com/jarischaefer/docker-librenms)

**Comment by jsenecal** [comment]
I submitted a PR(#2) to implement these features. Let me know if you need explanations or anything :)

**Comment by crazy-max** [comment]
Hi @jsenecal, I'll look at your PR and get back to you asap. From what I quickly saw, this would indeed allow LibreNMS to be implemented in a swarm environment :wink:

**Comment by crazy-max** [comment]
Closed by librenms/docker#3
