### ISSUE TITLE
Cron 

### ISSUE THREAD

**Issue by angdigi** [crazy-max/docker-librenms#7]
Receiving a cron error
Fail: The poller (bf91d09ef4d7) has not completed within the last 5 minutes, check the cron job.

I see this https://github.com/crazy-max/docker-librenms#cron-1

Can you give a bit more detail on how to get cron to run? If I run 
`docker exec -it librenms` can I then execute 
`docker run -d --name librenms-syslog-ng \
  --env-file $(pwd)/librenms.env \
  -p 514 -p 514/udp \
  -v librenms:/data \
  crazymax/librenms:latest /usr/sbin/syslog-ng -F`?

**Comment by crazy-max** [comment]
@angdigi First of all thanks for your donation :)
Can you give me the compose file you use please ?

**Comment by crazy-max** [comment]
@angdigi If this problem is still ongoing, open an issue on the new repository : https://github.com/librenms/docker
